#! /usr/bin/env bash

type zeek-script >/dev/null 2>&1 || exit 0

rc=0

for i in "$@"; do
    zeek-script format -ir "${i}" 2>&1 | grep -v '0 errors'
    test "${PIPESTATUS[0]}" -ne 0 && rc=1
done

exit ${rc}
