name: CI pipeline

on: push

env:
  ZEEK_PACKAGE: zeek-rc

jobs:
  test_ubuntu_24:
    runs-on: ubuntu-24.04

    steps:
      - name: Prepare
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y ninja-build ccache curl ca-certificates clang gpg
          sudo pip3 install btest zkg pre-commit

          # for bpftool
          sudo apt-get install llvm libelf-dev gcc-multilib

      - name: Install Zeek
        run: |
          echo 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_24.04/ /' | sudo tee /etc/apt/sources.list.d/security:zeek.list
          curl -fsSL https://download.opensuse.org/repositories/security:zeek/xUbuntu_24.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/security_zeek.gpg > /dev/null
          sudo apt update
          sudo apt install -y ${ZEEK_PACKAGE}
          echo "/opt/zeek-rc/bin:/opt/zeek/bin:$PATH" >> $GITHUB_PATH

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Test
        run: |
          make test

      - name: Check code
        run: |
          pre-commit run -a --show-diff-on-failure

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Test output
          path: |
            tests/.tmp
            zeek-agent/tests/.tmp

  publish_release:
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test_ubuntu_24]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build tarball
        run: |
          mkdir -p artifacts
          export base="zeek-agent-package-$(echo ${{ github.ref_name }} | sed 's/^v//')"; git archive --format tar.gz --output "artifacts/${base}.tar.gz" --prefix "${base}" ${{ github.ref_name }}

      - name: Prepare release message
        run: |
          cat CHANGES | awk '/^[0-9]+\./{ n++; next; } n < 2 { print }' >${{ runner.temp }}/release-msg
          echo "release_name=$(echo ${{ github.ref_name }} | sed 's/^v//')" >> $GITHUB_ENV

      - name: Display artifacts
        run: ls -al artifacts/*

      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          name: ${{ env.release_name }}
          body_path: ${{ runner.temp }}/release-msg
          files: |
            artifacts/*.tar.gz
